# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_dynamic.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
from qwt import *


from PyQt5 import QtCore, QtGui, QtWidgets
import sys




    

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 565)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 991, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.ManualControl = QtWidgets.QWidget()
        self.ManualControl.setObjectName("ManualControl")
        self.allOn = QtWidgets.QToolButton(self.ManualControl)
        self.allOn.setEnabled(True)
        self.allOn.setGeometry(QtCore.QRect(770, 420, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.allOn.setFont(font)
        icon = QtGui.QIcon.fromTheme("system-shutdown")
        self.allOn.setIcon(icon)
        self.allOn.setIconSize(QtCore.QSize(16, 16))
        self.allOn.setCheckable(False)
        self.allOn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.allOn.setObjectName("allOn")
        self.allOff = QtWidgets.QToolButton(self.ManualControl)
        self.allOff.setEnabled(True)
        self.allOff.setGeometry(QtCore.QRect(870, 420, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.allOff.setFont(font)
        icon = QtGui.QIcon.fromTheme("system-shutdown")
        self.allOff.setIcon(icon)
        self.allOff.setIconSize(QtCore.QSize(16, 16))
        self.allOff.setCheckable(False)
        self.allOff.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.allOff.setObjectName("allOff")
        self.group1 = QtWidgets.QGroupBox(self.ManualControl)
        self.group1.setEnabled(False)
        self.group1.setGeometry(QtCore.QRect(10, 50, 121, 351))
        self.group1.setTitle("")
        self.group1.setCheckable(False)
        self.group1.setObjectName("group1")
        self.pressureDisplay1 = QtWidgets.QDoubleSpinBox(self.group1)
        self.pressureDisplay1.setGeometry(QtCore.QRect(10, 50, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pressureDisplay1.setFont(font)
        self.pressureDisplay1.setObjectName("pressureDisplay1")
        self.pressureLabel1 = QtWidgets.QLabel(self.group1)
        self.pressureLabel1.setGeometry(QtCore.QRect(10, 30, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressureLabel1.setFont(font)
        self.pressureLabel1.setObjectName("pressureLabel1")
        self.pressureSlider1 = QwtSlider(self.group1)
        self.pressureSlider1.setGeometry(QtCore.QRect(20, 100, 71, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pressureSlider1.setFont(font)
        self.pressureSlider1.setObjectName("pressureSlider1")
        self.chanOnOff1 = QtWidgets.QToolButton(self.ManualControl)
        self.chanOnOff1.setEnabled(True)
        self.chanOnOff1.setGeometry(QtCore.QRect(70, 20, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.chanOnOff1.setFont(font)
        self.chanOnOff1.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon.fromTheme("system-shutdown")
        self.chanOnOff1.setIcon(icon)
        self.chanOnOff1.setIconSize(QtCore.QSize(16, 16))
        self.chanOnOff1.setCheckable(True)
        self.chanOnOff1.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.chanOnOff1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.chanOnOff1.setAutoRaise(False)
        self.chanOnOff1.setObjectName("chanOnOff1")
        self.chanLabel1 = QtWidgets.QLabel(self.ManualControl)
        self.chanLabel1.setGeometry(QtCore.QRect(10, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.chanLabel1.setFont(font)
        self.chanLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.chanLabel1.setObjectName("chanLabel1")
        self.tabWidget.addTab(self.ManualControl, "")
        self.TrajControl = QtWidgets.QWidget()
        self.TrajControl.setObjectName("TrajControl")
        self.trajPlot = QwtPlot(self.TrajControl)
        self.trajPlot.setGeometry(QtCore.QRect(170, 50, 801, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trajPlot.setFont(font)
        self.trajPlot.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.trajPlot.setLineWidth(2)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.trajPlot.setCanvasBackground(brush)
        self.trajPlot.setAutoReplot(True)
        self.trajPlot.setObjectName("trajPlot")
        self.stopTraj = QtWidgets.QToolButton(self.TrajControl)
        self.stopTraj.setGeometry(QtCore.QRect(10, 360, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.stopTraj.setFont(font)
        self.stopTraj.setStyleSheet("color: rgb(164, 0, 0);")
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.stopTraj.setIcon(icon)
        self.stopTraj.setIconSize(QtCore.QSize(64, 64))
        self.stopTraj.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.stopTraj.setObjectName("stopTraj")
        self.runTraj = QtWidgets.QToolButton(self.TrajControl)
        self.runTraj.setGeometry(QtCore.QRect(10, 300, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.runTraj.setFont(font)
        self.runTraj.setStyleSheet("color: rgb(78, 154, 6);")
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.runTraj.setIcon(icon)
        self.runTraj.setIconSize(QtCore.QSize(64, 64))
        self.runTraj.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.runTraj.setAutoRaise(False)
        self.runTraj.setArrowType(QtCore.Qt.NoArrow)
        self.runTraj.setObjectName("runTraj")
        self.loadTraj = QtWidgets.QToolButton(self.TrajControl)
        self.loadTraj.setEnabled(True)
        self.loadTraj.setGeometry(QtCore.QRect(10, 10, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loadTraj.setFont(font)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.loadTraj.setIcon(icon)
        self.loadTraj.setIconSize(QtCore.QSize(64, 64))
        self.loadTraj.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.loadTraj.setObjectName("loadTraj")
        self.label = QtWidgets.QLabel(self.TrajControl)
        self.label.setGeometry(QtCore.QRect(440, 400, 321, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.trajProgressBar = QtWidgets.QProgressBar(self.TrajControl)
        self.trajProgressBar.setGeometry(QtCore.QRect(220, 440, 751, 23))
        self.trajProgressBar.setProperty("value", 24)
        self.trajProgressBar.setTextVisible(True)
        self.trajProgressBar.setInvertedAppearance(False)
        self.trajProgressBar.setObjectName("trajProgressBar")
        self.saveData = QtWidgets.QCheckBox(self.TrajControl)
        self.saveData.setGeometry(QtCore.QRect(10, 440, 131, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveData.setFont(font)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.saveData.setIcon(icon)
        self.saveData.setChecked(True)
        self.saveData.setObjectName("saveData")
        self.trajNameDisplay = QtWidgets.QPlainTextEdit(self.TrajControl)
        self.trajNameDisplay.setEnabled(False)
        self.trajNameDisplay.setGeometry(QtCore.QRect(150, 10, 821, 31))
        self.trajNameDisplay.setObjectName("trajNameDisplay")
        self.tabWidget.addTab(self.TrajControl, "")
        self.configNameDisplay = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.configNameDisplay.setEnabled(False)
        self.configNameDisplay.setGeometry(QtCore.QRect(320, 10, 681, 31))
        self.configNameDisplay.setObjectName("configNameDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain_Window = QtWidgets.QMenu(self.menubar)
        self.menuMain_Window.setObjectName("menuMain_Window")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Configuration = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoad_Configuration.setIcon(icon)
        self.actionLoad_Configuration.setObjectName("actionLoad_Configuration")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-new")
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_Trajectory = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoad_Trajectory.setIcon(icon)
        self.actionLoad_Trajectory.setObjectName("actionLoad_Trajectory")
        self.menuMain_Window.addAction(self.actionSave)
        self.menuMain_Window.addAction(self.actionLoad_Configuration)
        self.menubar.addAction(self.menuMain_Window.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.chanOnOff1.clicked['bool'].connect(self.group1.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.allOn.setText(_translate("MainWindow", "All On"))
        self.allOff.setText(_translate("MainWindow", "All Off"))
        self.pressureLabel1.setText(_translate("MainWindow", "Pressure (psi)"))
        self.chanOnOff1.setText(_translate("MainWindow", "1"))
        self.chanLabel1.setText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ManualControl), _translate("MainWindow", "Manual"))
        self.stopTraj.setText(_translate("MainWindow", "Stop"))
        self.runTraj.setText(_translate("MainWindow", "Start"))
        self.loadTraj.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", "Time (s)"))
        self.saveData.setText(_translate("MainWindow", "Save Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TrajControl), _translate("MainWindow", "Trajectory"))
        self.menuMain_Window.setTitle(_translate("MainWindow", "Configuration"))
        self.actionLoad_Configuration.setText(_translate("MainWindow", "Load Config"))
        self.actionSave.setText(_translate("MainWindow", "Build Config"))
        self.actionLoad_Trajectory.setText(_translate("MainWindow", "Load Traj"))


app = QtWidgets.QApplication(sys.argv)

window = Ui_MainWindow()
window.setupUi(window)

app.exec_()
